package report

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
)

var pastelColors = []string{
	"#DBEAFE", // blue
	"#FEF3C7", // amber
	"#D1FAE5", // green
	"#FCE7F3", // pink
	"#E0E7FF", // indigo
	"#FED7AA", // orange
	"#CCFBF1", // teal
	"#EDE9FE", // violet
}

func writeHTML(rows []Row, serverName, reportDir, timestamp string) (string, error) {
	htmlPath := filepath.Join(reportDir, fmt.Sprintf("repo_grid_%s.html", timestamp))
	f, err := os.Create(htmlPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	// Assign colors to organizations
	orgColors := make(map[string]string)
	colorIdx := 0
	for _, r := range rows {
		if r.Organization == "-" {
			continue
		}
		if _, exists := orgColors[r.Organization]; !exists {
			orgColors[r.Organization] = pastelColors[colorIdx%len(pastelColors)]
			colorIdx++
		}
	}

	title := "Repository Access Grid"
	if serverName != "" {
		title += " — " + html.EscapeString(serverName)
	}

	// Write HTML document
	fmt.Fprintf(f, `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>%s</title></head>
<body style="font-family:Arial,Helvetica,sans-serif;margin:0;padding:20px;background:#ffffff;">
<div style="max-width:1200px;margin:0 auto;">
<h2 style="margin:0 0 4px 0;">%s</h2>
<p style="color:#666;font-size:0.85em;margin:0 0 16px 0;">Generated: %s</p>
<table style="width:100%%;border-collapse:collapse;font-size:0.9em;">
<tr style="background:#1f2937;color:#ffffff;">
  <th style="padding:10px 12px;text-align:left;">Repository</th>
  <th style="padding:10px 12px;text-align:left;">Description</th>
  <th style="padding:10px 8px;text-align:center;width:30px;">Type</th>
  <th style="padding:10px 12px;text-align:left;">Owner</th>
  <th style="padding:10px 12px;text-align:left;">Users with Access</th>
</tr>
`, title, title, html.EscapeString(timestamp))

	// Write rows
	for _, r := range rows {
		bgColor := "#F5F5F5"
		typeLabel := "U"
		if r.Organization != "-" {
			bgColor = orgColors[r.Organization]
			typeLabel = "O"
		}

		// Build user pills
		var pills []string
		for _, u := range r.Users {
			pills = append(pills, fmt.Sprintf(
				`<span style="display:inline-block;padding:2px 10px;margin:2px;background:#e0e0e0;border-radius:12px;font-size:0.8em;">%s</span>`,
				html.EscapeString(u),
			))
		}
		usersHTML := strings.Join(pills, " ")
		if usersHTML == "" {
			usersHTML = "-"
		}

		// Repo link
		repoCell := html.EscapeString(r.Repository)
		if r.URL != "" {
			repoCell = fmt.Sprintf(`<a href="%s" style="color:#1d4ed8;text-decoration:none;">%s</a>`,
				html.EscapeString(r.URL), html.EscapeString(r.Repository))
		}

		fmt.Fprintf(f, `<tr style="background:%s;border-bottom:1px solid #e5e7eb;">
  <td style="padding:8px 12px;">%s</td>
  <td style="padding:8px 12px;">%s</td>
  <td style="padding:8px 8px;text-align:center;font-size:0.85em;font-weight:bold;">%s</td>
  <td style="padding:8px 12px;">%s</td>
  <td style="padding:8px 12px;">%s</td>
</tr>
`, bgColor, repoCell, html.EscapeString(r.Description), typeLabel, html.EscapeString(r.Owner), usersHTML)
	}

	// Footer
	fmt.Fprintf(f, `</table>
<p style="color:#999;font-size:0.75em;margin-top:12px;text-align:center;">Generated by Infuser Go</p>
</div></body></html>`)

	return htmlPath, nil
}
